version: '3.8'
services:
  dbpostgresql:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=scheduling-tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  scheduling-tasks:
    image: scheduling-tasks
    build: ./
    ports:
      - "8080-8090:8080"
    environment:
      - SCHEDULING_TASK_DB_URL=dbpostgresql
    depends_on:
      - dbpostgresql